Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace PharmaStire_PS.Controllers
{
    public class AboutController : Controller
    {
        public ViewResult Index() => View();
    }
}

Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PharmaStire_PS.Infrastructure;
using PharmaStire_PS.Models;
using Microsoft.AspNetCore.Mvc.NewtonsoftJson;
using Newtonsoft.Json.Serialization;
using Microsoft.AspNetCore.Mvc.Core;
using Microsoft.AspNetCore.Mvc.Formatters.Json;
using Microsoft.AspNetCore.Http.Extensions;

using Microsoft.AspNetCore.Mvc.Formatters;
using Microsoft.Extensions.Options;
using PharmaStire_PS.Models.ViewModels;

namespace PharmaStire_PS.Controllers
{
    //Для обработки щелчков на кнопках AddТоCart понадобится создать контроллер.
    //Добавим в  папку Controllers файл класса по имени CartController.cs

    //Для сохранения и извлечения объектов Cart применяется средство состояния
    //сеанса ASP.NET, с которыми взаимодействует метод GetCart() . Промежуточное
    //программное обеспечение, зарегистрированное в предыдущем разделе, использует
    //сооkiе-наборы или переписывание URL, чтобы ассоциировать вместе множество
    //запросов от определенного пользователя с целью формирования отдельного сеанса
    //просмотра. Связанным средством является состояние сеанса, которое ассоциирует
    //данные с сеансом. Ситуация идеально подходит для класса Cart: мы хотим, чтобы
    //каждый пользователь имел собственную корзину, и она сохранялась между запросами.
    //Данные, связанные с сеансом, удаляются по истечении времени существования сеанса
    //(обычно из-за того, что пользователь не отправляет запрос какое-то время,
    //т.е.управлять хранилищем или жизненным циклом объектов Cart не придется.
    //В методах действий AddToCart () и RemoveFromCart () применялись имена параметров,
    //которые соответствуют именам элементов input в НТМL-формах, созданных в представлении
    //ProductSummary. cshtml.Это позволяет инфраструктуре MVC ассоциировать входящие
    //переменные НТГР-запроса POST формы с параметрами и означает, что делать что-то
    //самостоятельно для обработки формы не нужно.Такой процесс называется привязкой
    //модели и с его помощью можно значительно упрощать классы контроллеров

    public class CartController : Controller
    {
        private IProductRepository repositoty;

        //services
        private Cart cart;

        //public CartController(IProductRepository repo)
        //{
        //    repositoty = repo;
        //}

        //services
        public CartController(IProductRepository repo, Cart cartService)
        {
            repositoty = repo;
            cart = cartService;
        }

        public RedirectToActionResult AddToCart(int productId, string returnUrl)
        {
            Product product = repositoty.Products
                .FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
            {
                //Cart cart = GetCart();
                //SaveCart(cart);

                cart.AddItem(product, 1);
            }

            return RedirectToAction("Index", new {returnUrl});
        }

        public RedirectToActionResult RemoveFromCart(int productID, string returnUrl)
        {
            Product product = repositoty.Products
                .FirstOrDefault(p => p.ProductID == productID);
            if (product != null)
            {
                //Cart cart = GetCart();
                //SaveCart(cart);

                cart.RemoveLine(product);
            }

            return RedirectToAction("Index", new {returnUrl});
        }


        //private Cart GetCart()
        //{
        //    Cart cart = HttpContext.Session.GetObjectFromJson<Cart>("Cart") ?? new Cart();
        //    return cart;
        //}

        //private void SaveCart(Cart cart)
        //{
        //    HttpContext.Session.SetObjectAsJson("Cart", cart);
        //}

        //public IActionResult Index()
        //    => Json(new { message = "Test" });
        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                //Cart = GetCart(),
                Cart = cart,
                ReturnUrl = returnUrl
            }); ;
        }
        
    }
}

Views/Shared/ProductSammary.cshtml
@*Создадим частичное представление, являющееся фрагментом содержимого,
    которое можно внедрять в другое представление подобно шаблону.*@

@model Product




<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Name
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>

    @*Обновлено для включения кнопки AddТоCart*@
    @*<div class="card-text p-1">@Model.Description</div>*@
    @*Мы добавили элемент form, содержащий скрытые элементы input, которые
        устанавливают значение ProductID из модели представления и URL, куда
        браузер должен возвращаться после обновления корзины. Элемент form и
        один из элементов input конфигурируются с использованием встроенных
        вспомогательных функций дескрипторов, что является удобным способом
        генерирования форм, которые содержат значения модели и нацелены на
        контроллеры и действия в приложении. Во втором элементе input применяется
        расширяющий метод, созданный для установки URL возврата. Кроме того,
        добавлен элемент button, который будет отправлять форму приложению.*@

    <form id="@Model.ProductID" asp-action="AddToCart"
          asp-controller="Cart" method="post">
        <input type="hidden" asp-for="ProductID" />
        <input type="hidden" name="returnUrl"
               value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            @Model.Description
            <button type="submit"
                    class="btn btn-success btn-sm pull-right" style="float: right">
                Add To Cart
            </button>

        </span>

    </form>
</div>




@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Shared/_AdminLayout.cshtml
@*Каждый заказ отображается с кнопкой Ship(Отгрузить), которая отправляет форму
    методу действия MarkShipped(). С помощью свойства Layout для представления
    List указана другая компоновка, которая переопределяет компоновку. Заданную
    в файле_ViewStart. cshtml.*@
@*306 Для добавления компоновки создадим в папке Views/Shared файл
    по имени AdminLayout. cshtml с применением шаблона элемента
    MVC View Layout Page (Страница компоновки представления МVС)
        <link rel="stylesheet" asp-href-include="/lib/bootstrap-4.0.0-alfa/dist/css/*.css" />
        <link rel="stylesheet" asp-href-include="/lib/bootstrap-4.5.0-dist/dist/css/*.css" />


*@


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @*<link rel="stylesheet" asp-href-include="/lib/bootstrap-4.5.0-dist/dist/css/*.css" />*@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" asp-href-include="/lib/fontawesome-free-5.14.0-web/css/*.css" />

    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>

</head>

<body class="m-1 p-1">

    <div class="bg-info p-2 row">
        <div class="col">
            <h4>@ViewBag.Title</h4>
        </div>
        <div class="col-2">
            <a class="btn btn-sm btn-primary"
               asp-action="Logout" asp-controller="Account">Log Out</a>
        </div>
    </div>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success mt-1">@TempData["message"]</div>
    }
    @RenderBody()
</body>
</html>

@section Scripts {
    @*<script src="/lib/jquery/dist/jquery.min.js"></script>
        <script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>*@
    <partial name="_ValidationScriptsPartial.cshtml" />
    <localization-validation-scripts></localization-validation-scripts>
}

@*Включение проверки достоверности на стороне клиента не приводит
    к каким-то визуальным изменениям. Но ограничения. Которые указаны
    с помощью атрибутов .примененных к классу модели С#, вступают
    в силу на уроне браузера, предотращая отправку пользователем
    формы с недопустимыми данными и обеспечивая немедлен­ный отклик при наличии проблемы.*@
@*
    https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1
         You may not be able to enter decimal commas in decimal fields.
    To support jQuery validation for non-English locales that use a comma
    (",") for a decimal point, and non US-English date formats, you must
    take steps to globalize your app.

    https://quares.ru/?id=55285
         установить пакет nuget:


    Install-Package LazZiya.TagHelpers -Version 2.1.0


        добавить LazZiya.TagHelpers в _ViewImports:

    @using LazZiya.TagHelpers
    @addTagHelper *, LazZiya.TagHelpers

        зарегистрируйте вспомогательный компонент тега проверки локализации при запуске:


    services.AddTransient<ITagHelperComponent, LocalizationValidationScriptsTagHelperComponent>
        ();


        добавьте тег в раздел скриптов на странице для проверки локализованных полей ввода (должен быть также загружен файл по умолчанию _ValidationScriptsPartial.cshtml):

        <partial name="_ValidationScriptsPartial.cshtml" />
        <localization-validation-scripts></localization-validation-scripts>

        Этот TagHelper автоматически определит текущее имя культуры и добавит все необходимые сценарии для проверки локализованных значений.*@

Views/Shared/_Layout.cshtml
@*стр218


    Файл запуска представления,
    указывает, что в качестве стандартной компоновки должен
    выступать файл по имени Layout.cshtml, так что начальную
    стилизацию Bootstrap мы применим именно к нему


    asp-href-include="/lib/bootstrap/dist/**/*.min.css"
    asp-href-include="/lib/twitter-bootstrap/dist/**/*.css"
          asp-href-include="/lib/bootstrap/dist/**/*.css"

              asp-href-include="/lib/bootstrap-4.5.0-dist/dist/**/*.css"
          asp-href-include="/lib/bootstrap-4.0.0-alfa/dist/**/*.css"

    bootstrap-4.5.0-dist
*@

<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <META NAME="Robots" CONTENT="INDEX,FOLLOW">
    <META NAME="description" CONTENT="Данный сайт содержит информацию для любителей ... ">
    <META NAME="keywords" CONTENT="реклама">
    <meta name="author" content="Заболотный Константин зпи-зп92">
    @*<link rel="stylesheet"
        asp-href-include="/lib/bootstrap-4.5.0-dist/dist/**/*.css"
        asp-href-exclude="**/*-reboot*,**/*-grid*" />*@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" asp-href-include="/lib/fontawesome-free-5.14.0-web/css/*.css" />

    <title>PharmacyStore</title>
    <style>
        .dropdown-content {
            display: none;
            position: absolute;
            /*            background-color: #f1f1f1;
        */ min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

            /* Links inside the dropdown */
            .dropdown-content a {
                display: block;
            }
        .show {
            display: block;
        }
    </style>
</head>
<body>







    <nav class="navbar navbar-dark navbar-expand-sm navbar-toggleable-sm bg-dark " role="navigation">

            @*<div id="categories" class="col-3">
                        Put somesing useful here later
                        Текс заполнителя заменен вызовом метода Component .InvokeAsync().
                    Аргументом метода является имя класса компонента без части View Component. т.е .
                    с помощью NavigationMen указывается класс NavigationMenuViewComponent.
                    Запустив приложение, можно заметить. Что вывод из метода InvokeAsync() включен НТМL­разметку.
                        @await Component.InvokeAsync("NavigationMenu")
                    </div>boxboxclass="container"
                </div>*@


            <div>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternal" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <a class="   navbar-brand " asp-area="" asp-page="/Index">Аптека</a>

            </div>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse" id="navbarToggleExternal">
                <ul class="navbar-nav flex-grow-1">

                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-page="/Privacy">Конфіденційність</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-action="Index" asp-controller="About">Про_пристрій_користувача</a>
                    </li>

                </ul>
            </div>


            @await Component.InvokeAsync("CartSummary")













        </nav>


        <div class="row m-0 p-0">
            <div id="categories" class="col-3">
                @*Put somesing useful here later*@
                @*Текс заполнителя заменен вызовом метода Component .InvokeAsync().
                    Аргументом метода является имя класса компонента без части View Component. т.е .
                    с помощью NavigationMen указывается класс NavigationMenuViewComponent.
                    Запустив приложение, можно заметить. Что вывод из метода InvokeAsync() включен НТМL­разметку.*@
                @await Component.InvokeAsync("NavigationMenu")
            </div>


            <div class="col-9">
                @RenderBody()
            </div>
            <footer class="footer" style="text-align:center">
                <p>Заболотный Константин зпи-зп92
                    <a href="mailto:kastantin.knu@gmail.com?subject=Вопрос по HTML">
                        Відправити_відгук
                    </a>
                </p>
            </footer>
        </div>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

        @RenderSection("Scripts", required: false)
    </body>
</html>